### ISSUE TITLE
Making releases

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#109]
Hey Jason,

I just realized that I've never made a release on the new website. Assuming generated binaries and installers are available, how do we go about making a release?

**Comment by markknol** [comment]
It looks like you can append a new version in this json file, https://github.com/HaxeFoundation/haxe.org/blob/master/www/website-content/downloads/versions.json and create a subfolder with all needed content. Not sure if anything else is needed.

**Comment by Simn** [comment]
@jasononeil: I messed something up but I have no idea what. Help!

**Comment by Simn** [comment]
I think I got it working now but I had massive issues with deployment. It started with an extra comma in versions.json which travis didn't care about because it doesn't check any exit codes. I still can't deploy properly through travis so I updated manually via SSH.

Please fix the mess I made!

**Comment by jasononeil** [comment]
Oh man I forgot about the whole "doing a release" thing.  I had intended to clean up the release code before 3.2, but that idea got lost somewhere.  Now that travis is (*usually*) working there's no reason for us to be loading all the version information at runtime without checking it's valid. 

So what happened:

* The missing comma wasn't checked by travis, it deployed, the JSON failed to load, downloads list broken.  To workaround this I'll start loading those JSON files at compile time so the build fails if the JSON is invalid, and Travis will let you know.

* The travis deploy stopped working because of unix permissions and git and I don't know what.  Basically some files had been modified, or some git commands run, as a different user, and then Travis couldn't do it's "git pull" command because it didn't have permissions to change those files.  I'm going to try clean up the directory on the server so all the files are owned by the user/group "www-haxe" and Travis uses that group, and hopefully anything you, me or Nicolas do will keep those permissions and not break things.  Despite using Linux full time I still get confused by the permission system sometimes.

On a different note, it's possible to leave "3.1.3" as the "current" release until 3.2 is official, and skip the release candidate.  Would you like to do that?

**Comment by jasononeil** [comment]
Also, I've made an issue about Travis not failing when the deployment fails:

https://github.com/ufront/ufront/issues/12

**Comment by jasononeil** [comment]
Okay @Simn I've got the travis deploys working again.  It's now deploying using the "www-haxe" user.  If you're going to make any manual changes on the server it's probably worth making sure the files belong to that user, and if we ever get stuck we can do a bulk `chown -R www-haxe` to try fix things up.

Also, if you email me your public key I can add it to the `www-haxe` user so you can run deployments without travis.

I'll get on to reading the JSON files and verifying them at compile time in a day or two.

**Comment by Simn** [comment]
Sorry about the file mess, I thought I could "quickly fix" something and didn't realize there was a git repository running there. Also I was panicking a bit yesterday. :)

I still don't understand why index.n didn't deploy anymore, but I'm just glad it's working now. Thanks!
