### ISSUE TITLE
RC should not be on landing page

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#110]
We should maybe not land on a RC when clicking on "Download" on haxe.org, but instead on the latest stable

**Comment by Simn** [comment]
So we get even less people to test it?

**Comment by ncannasse** [comment]
So that people new to haxe don't download a RC accidentaly

**Comment by Simn** [comment]
I've taken down the whole thing until further notice.

**Comment by ncannasse** [comment]
That should still be filtered when we re-release the RC (we could navigate Next to RC, then Next to Nightly Builds)

Also we have to warn @skial not to publish information about a RC until it's actually announced by ourselves :)

**Comment by Merelleya** [comment]
I'm not sure where it initially came from. Part of it was surely caused by my announcing the release 2 weeks a go through facebook, so people were waiting for it on Sunday.

**Comment by Simn** [comment]
There's nothing to filter here, I explicitly set the RC as the current release in the config. I'll just not do that next time.

As for the release announcement, it was really silly but I think it turned out alright. The nice thing is that now nobody can blame us because we didn't announce the thing.
