### ISSUE TITLE
Download url convention

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe.org#111]
It is hard to determine the direct download url of a particular version, particularly for the RC versions.
Notice the subtle difference between rc/rc1/rc2 and the number of ".0" in the zip file names:
 * 3.0.0-rc.1 => http://haxe.org/website-content/downloads/3,0,0-rc,1/downloads/haxe-3.0.0-rc-win.zip
 * 3.0.0-rc.2 => http://haxe.org/website-content/downloads/3,0,0-rc,2/downloads/haxe-3.0.0-rc2-win.zip
 * 2.0.0-rc.1 => http://haxe.org/website-content/downloads/2,0,0-rc,1/downloads/haxe-2.0-rc1-win.zip

Given the [current internal file name convention](https://github.com/HaxeFoundation/haxe.org/blob/master/src/app/api/DownloadApi.hx#L65) only specify the suffix ("win.zip", "osx.tar.gz" etc.), I would like to know if is it possible to provide additional routings like the following?
* http://haxe.org/website-content/downloads/3,0,0-rc,1/downloads/win.zip => http://haxe.org/website-content/downloads/3,0,0-rc,1/downloads/haxe-3.0.0-rc-win.zip

The current url may still work for compatibility reason.

**Comment by jasononeil** [comment]
I'm going to do some work on the downloads / releases this week to ease the release process anyway, so it will be a good time to tackle this.

See also comments on 

https://github.com/dpeek/hvm/issues/3
https://github.com/dpeek/hvm/issues/4

One of the suggestions is to keep the binaries (even stable ones) on builds.haxe.org with a consistent naming scheme.

**Comment by jasononeil** [comment]
@andyli does this work for you?

All the version numbers in the folder and path should match, eg

http://haxe.org/website-content/downloads/3.0.0-rc.1/downloads/haxe-3.0.0-rc.1-win.zip

So you can insert the same version string to consistently get the path you want.  Notice I've also changed the folders to use "3.0.0-rc.1" instead of "3,0,0-rc,1".  Redirects are in place for the old paths.

Feel free to comment and re-open if you would prefer a different solution.

**Comment by andyli** [comment]
Looks perfect! Thanks!
