### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#116]
Where is the 404 page located? Can i update it somewhere? It looks outdated http://haxe.org/manual/target-php.html

**Comment by jasononeil** [comment]
Please do!

https://github.com/HaxeFoundation/haxe.org/blob/master/src/app/view/error.html

It uses Haxe string interpolation rather than regular templating... the reason is it's an error handler that might be handling an error in loading templates etc.

If you're just updating the layout it should be easy enough.  If you want more control over how the actual error is displayed let me know and I'll help you out.
