### ISSUE TITLE
haxe.org and lib.haxe.org is extremely slow right now

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe.org#122]
As title. I guess a reboot is needed?

**Comment by jasononeil** [comment]
There was a memory leak in the `minject` library used by ufront.  Possibly this issue: https://github.com/massiveinteractive/minject/issues/30

The issue is fixed in the unreleased v2 branch of minject.  For now I'm using a git submodule to reference this lib until it is released.

Fixed by 944f90b990b678349f33a2517d7006f2ee00ee66
