### ISSUE TITLE
Get the binaries out of git

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#201]
At the moment we have all binaries as part of the git repository which is really dumb. It would be nice to have them separately.

**Comment by andyli** [comment]
I've just had a look into it. I think it is a good idea to use [Git LFS](https://git-lfs.github.com/), which [Github supports](https://help.github.com/articles/versioning-large-files/), to store the binaries. People who want to get/commit the binaries will have to install Git LFS. For those who don't need the binaries, they don't have to do anything, and they will get some plain text "pointer" files instead of the binaries when they clone.

To convert our repo to use LFS (i.e. to move the existing committed files to LFS), we need a one-time force-push to the github repo. After that, existing cloned repos will not be able to pull normally. To get the converted repo, either 1. delete the old repo and clone again, or 2. `git fetch && git reset --hard origin/<branch>` for each of the branches.

Before the conversion, I need to look into installing LFS on our server/TravisCI. I will let you know after some testing.

**Comment by ibilon** [comment]
What about a simple ftp server?
Since the binaries aren't versionned and don't need to be in the repo at all.

**Comment by Simn** [comment]
FTP server, fancy git solutions, burn them on cd-rom and mail them... I don't really mind as long as they're gone from the repository. :)

**Comment by markknol** [comment]
I would propose to put them here:
https://github.com/HaxeFoundation/haxe.org/releases

**Comment by ibilon** [comment]
That would be a good place to put them,
but might not be easy to use in the deployment

**Comment by markknol** [comment]
We can just link directly to the binary on Github ?

**Comment by ibilon** [comment]
Right, I guess we could :)

**Comment by markknol** [comment]
Update: I've put all downloads (binaries + api) including the release notes to this page:
https://github.com/HaxeFoundation/haxe/releases

Now as I understand the source correctly, the releases.json files is modified and cached compile-time. and the sources of the downloads are read from filesystem. We need to change this, because if we remove the soures from the repo, there are no downloads on filesystem anymore. So we either have to manually add the names of the downloads to the releases.json or we load them using the Github API. I found it is relative easy to grab this data using this url https://api.github.com/repos/haxefoundation/haxe/releases We can match against the tag_name which is available in both json files already.
For me it doesn't feel easy to change the download code, maybe someone else can pick this up?

cc @jasononeil

**Comment by ibilon** [comment]
Done it the new code.
