### ISSUE TITLE
OpenSUSE Not Updated - Currently version 3.2.1 is avilable on OpenSUSE

### ISSUE THREAD

**Issue by mtelesha** [HaxeFoundation/haxe.org#231]
> The Haxe Foundation maintains the Haxe and Neko RPM packages in the openSUSE:Factory repository. The packages are up-to-date most of the time. However, when a new version of Haxe is released, it will take a few days, up to 2 weeks, to be accepted by openSUSE:Factory.

https://build.opensuse.org/package/show/openSUSE:Factory/haxe = 3.2.1

https://build.opensuse.org/package/show/devel:languages:haxe/haxe   = 3.2.1

OpenSUSE is my Development Machine's OS and I was a tiny bit disappointed that it was behind.

**Comment by andyli** [comment]
This is intended because currently Haxe 3.4, and 3.3, are just release candidates. They are not really releases. I will update the packages when 3.4 is final.

In the mean time, you may try to compile Haxe from source and it's actually pretty simple: https://haxe.org/documentation/introduction/building-haxe.html
