### ISSUE TITLE
Linux binaries aren't listed in the download page

### ISSUE THREAD

**Issue by mrcdk** [HaxeFoundation/haxe.org#264]
Windows and OSX have the option to download their binaries but Linux only offers the option to download it from the different package managers. I think that there should be a button to download Linux binaries too.

I know there is a link to download them like http://haxe.org/download/file/3.4.2/haxe-3.4.2-linux64.tar.gz/

**Comment by andyli** [comment]
I purposely removed them from the download page in https://github.com/HaxeFoundation/haxe.org/commit/930f65c671b6ef85070707c94148b4a648aa9d67.
Mainly because we have no info on how to install them, and I'm too lazy to write down all the corner cases of that...

Any reason you want to get them?

**Comment by ibilon** [comment]
It's useful when you don't have root access (and so to the package manager) and don't want to compile haxe yourself.

**Comment by mrcdk** [comment]
Most people won't need to, but I was trying to install it by hand so I could go from one version to another.

**Comment by jcward** [comment]
Yes, I just came here to file this same issue. This irritates me as well for these reasons:

- I don't like the package managers because I prefer to know exactly what's going on when installing software.
- As said above, package managers require root
- Package managers are a pain and repos always manage to fall out of date (does it have the right version of Haxe for my flavor of linux, which are numerous.)
- Switching between versions of Haxe requires downloading each binary tar and unzipping them in various locations.

Regarding the [commit message](https://github.com/HaxeFoundation/haxe.org/commit/930f65c671b6ef85070707c94148b4a648aa9d67), IMO it's a power user thing to want to install things manually and switch between versions. You don't need to provide instructions for it.

In any case, if anyone else lands here, there appear to be two workarounds:

For the latest version of Haxe:

1) On the [download page](http://haxe.org/download/), right-click the "OSX binaries", and copy link
2) Paste that link into the address bar, but change `osx` to `linux64` (or `linux32`)

If that ever stops working, or you want a specific version of Haxe:

1) Go to the Haxe [github page](https://github.com/HaxeFoundation/haxe)
2) Under Tags dropdown, choose the version you want (e.g. **3.4.2**)
3) Now, on the right it shows a commit number, e.g. `890f8c7`
4) Go to the [nightly builds](http://builds.haxe.org) page, choose your OS, e.g. `linux64`
5) Search for the archive commit number, e.g. `haxe_2017-03-20_master_890f8c7.tar.gz` (if it was a major release probably has *master* in the name instead of *development*)

**Comment by ibilon** [comment]
They're back.
