### ISSUE TITLE
how about integrating haxe.io as news/blog

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe.org#39]
that would be great ;)

**Comment by Merelleya** [comment]
Just a quick note on blogs and fresh content.

Having new blog-like content is still very important for any website. It's not that it's not worth it anymore, it's just a lot of work. But, if you are willing to put in the hours needed for nice features and posts, the payoff is definitely there.

I would love to have the roundups featured more prominently and lately (since the announcement of wwx 2015) I have also felt the need for a news section. I know you all talk with each other by e-mail and chat, but some of the website's purposes are:

1. Showcasing Haxe and what can be done with it
2. Providing a point of entry for new users/interested parties

It's basically your storefront window, so it should be up to date and provide actual insight as well as make the reader/viewer want to find out more about Haxe, the foundation and what is going on.

I think a news section would support this beautifully and having Brendon endorsed as "official roundup" is more than overdue.

I would leave the decision up to him (whether he prefers a prominent link, or share the official news section). 

A twitter box could be useful as well. I would implement it and then see (via analytics) if people actually interact with it. Another possibility would be to link to the hashtag search #haxe on twitter.

In light of WWX approaching fast, I would really love to have the News and the Roundups (if possible) soon. 

Let's get to it, guys!

Fiene

**Comment by Simn** [comment]
I'm still against a twitter box. We should avoid fragmentation of possible news sources and there's always the problem of quality control. The content work @skial is doing is invaluable and I don't want to taint it with what the peasants have to say on twitter. :)

**Comment by ncannasse** [comment]
I actually setup twitter https://twitter.com/haxe_org for this purpose, which is to provide an important-news-only account for important events. We could have have someone taking care of it with that in mind (vs https://twitter.com/haxelang which is more community-oriented), posting important announcements as well as Skial weekly roundups

**Comment by Merelleya** [comment]
I am happy to deal with the twitter account, however, I think It would still be good to feature it on the website, seeing as that is the place you refer people to who are "looking" at Haxe for the first time. Also, twitter is very short-lived and retrieving information is tedious. I think it's very important to have a place where you can store information more "permanently" and later go back and look it up.

**Comment by skial** [comment]
> I think a news section would support this beautifully and having Brendon endorsed as "official roundup" is more than overdue. I would leave the decision up to him (whether he prefers a prominent link, or share the official news section).

I don't think you need to officially endorse the roundups, haxe.io is already linked to so thats enough of an endorsement I feel. I wouldn't turn down a more prominent link :smile:.

> A twitter box could be useful as well. I would implement it and then see (via analytics) if people actually interact with it. Another possibility would be to link to the hashtag search #haxe on twitter.

If you decide to have a twitter box it might be better to show a curated list of tweets instead of just #haxe which receives quite a bit of spam.

I currently keep an eye on the following search `#haxe OR #openfl OR #snowkit OR #snowkitcommunity OR #luxeengine OR @haxelang OR @haxeflixel OR @haxepunk OR #transpiler OR #transpilers OR #awe6`.

If you dare to interact with the twitter api, @NicoM1 [haxebot](https://github.com/NicoM1/HaxeBot/blob/master/src/Main.hx#L24) has already done some work on what to search for, block and filter.

**Comment by Simn** [comment]
I'd be okay with a twitter box for some managed account like `haxe_org` if someone actually posts there. That's the thing though: we (as in the Haxe Foundation) don't usually have much news to share. This makes the whole thing seem rather inactive.

**Comment by jasononeil** [comment]
Last update on @ haxe_org was July 29, so there would need to be some new content.  Even just retweeting the haxe.io links each week, plus release announcements and event news?

Adding the twitter box is dead easy.  The code is:

```
            <a class="twitter-timeline"  href="https://twitter.com/haxe_org" data-widget-id="570353343810109440">Tweets by @haxe_org</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
```

The next question is, where to put it?  In terms of homepage sections, I'm thinking:

* Logo + Download links
* Platforms | Quote
* __News Highlight | Twitter__
* Learn More
* Taste of Haxe | Quote
* Haxe Toolkit
* Haxe Foundation | Partners
* Evaluating Haxe | Quote

Where News Highlight would be:

* Promo for WWX
* Summary of WWX
* New versions
* Featured haxelib / showcase

or something similar.  I could work with @Merelleya to get the first WWX promo content up and in place?

**Comment by Merelleya** [comment]
so we can agree on the following:

* We will implement a News box on the front page
* That box will be fed with the Roundups, our Showcases and our News Posts
* It will display something like title-summary-link-maybe picture
* Showcases and News posts differ in that the Showcases are basically human interest stories and the News shorter announcements about WWX, releases, new partners, etc.
* we might want to include Roundups, Announcements and Showcases as separate items in the menu under "News" or something. That way, when you go into that category, you see all content that has been put up there.
* we can color code the entries in the news box or give them tags so that its easily visible what is a roundup, what is our own announcement and what is a showcase
