### ISSUE TITLE
Constant URL for latest stable haxe binaries.

### ISSUE THREAD

**Issue by grisevg** [HaxeFoundation/haxe.org#83]
Hi,

It would be very useful to have url that always points to the latest stable haxe binaries (a separate one for each platform), so automated scripts (e.g. chef) could get and install it.

I know that http://builds.haxe.org/ has a constant link to latest nightly build, but there is no link to latest stable one.

Thank you

**Comment by Simn** [comment]
We'll need one link for each download. We should follow the names that builds.haxe.org uses and make it available as `http://haxe.org/download/latest/windows`, `http://haxe.org/download/linux64` etc.

@jasononeil: Can you set this up?

**Comment by jasononeil** [comment]
If we can guarantee that our download files will follow the same naming convention into the future, then this should be easy enough. 

Currently the names are like:

```
haxe-3.1.3-linux32.tar.gz
haxe-3.1.3-linux64.tar.gz
haxe-3.1.3-osx-installer.pkg
haxe-3.1.3-osx.tar.gz
haxe-3.1.3-raspi.tar.gz
haxe-3.1.3-win.exe
haxe-3.1.3-win.zip
```

See [3.1.3](https://github.com/HaxeFoundation/haxe.org/tree/master/www/website-content/downloads/3%2C1%2C3/downloads) and [3.1.2](https://github.com/HaxeFoundation/haxe.org/tree/master/www/website-content/downloads/3%2C1%2C2/downloads)

If we keep with this convention, then I could do:

```haxe
	@:route("/latest/$platformDownload")
	public function doLatestStableDownload( platformDownload:String ) {
		var currentVersion = apiSite.getCurrentVersion( versionRepo() );
		var versionDir = currentVersion.replace( '.', ',' );
		var file = 'haxe-$currentVersion-$platformDownload';
		var directDownloadLink = '/${versionRepo()}/$versionDir/downloads/$file';
		return new RedirectResult( directDownloadLink )
	}
```

This would redirect:

* `/download/latest/win.exe` -> `/website-content/downloads/3,1,3/downloads/haxe-3.1.3-win.exe`
* `/download/latest/osx-installer.pkg` -> `/website-content/downloads/3,1,3/downloads/haxe-3.1.3-osx-installer.pkg`

etc.

Possible issues:

* We bypass the `/download/file/3.1.3/haxe-3.1.3-win.exe` page, which we were using so Google Analytics could pick up on the number of downloads.  Not sure how to workaround this... We could track the numbers ourselves separate to the GA numbers, but then we don't get the pretty graphs.
* If you ever stop offering a particular binary, eg "raspi.tar.gz", then `/latest/raspi.tar.gz` would 404, rather than find the latest version that *did* exist.  We could work around this with a slightly more complex solution than the one proposed above.

**Comment by Simn** [comment]
I'm fine with keeping file name conventions. They are generated by the release helper script anyway: https://github.com/waneck/hxbuilds/blob/master/release-helper/src/Release.hx#L15

**Comment by Simn** [comment]
Does anyone know how we could support this? Maybe @kevinresol?

**Comment by kevinresol** [comment]
hm... I have zero knowledge about the site.
Needa take some time to read through the source, I can try to find some time for that.
But would be best if @jasononeil spend some short time on it.

**Comment by kevinresol** [comment]
> We bypass the /download/file/3.1.3/haxe-3.1.3-win.exe page, which we were using so Google Analytics could pick up on the number of downloads.

I wonder if we can simply create the same page for `latest` on which browser will auto start downloading the latest binary. Then we will have GA for hits on `latest`. And since release dates are known we can sort out what the latest version is for each period.

**Comment by markknol** [comment]
If someone is going to look at this, then it might also be a good time to pick this up too https://github.com/HaxeFoundation/haxe.org/issues/201

**Comment by ibilon** [comment]
Stable html landing page with releases notes, links, ...
https://haxe.org/download/file/latest/haxe-latest-linux64.tar.gz/

Direct url
https://haxe.org/website-content/downloads/latest/downloads/haxe-latest-win.exe
